travis:
  secure:
    BINSTAR_TOKEN: FIiL3OOd/5tt6VR+OKBD08mA21PW41VMmMc5TpZ/Yli8hlrV8GKsy+3jbP9S4p0rOtjoDmlo1ymLqep0xUR5vdZV6KHQ6WGK3041q4Qg/YYgf3WKdqAYo6PX/MOZnJwMN81iHCqP1s3UH4qMBBcDZ7SlYlcgtLWfRuv99Sq9UNa3I2ZyCiO+6c+0E6cKAAt30ImkSF6Ex6mpXLtXyCl1N6MA8GFBqXEpDunSo9acWzz2dTSmUjD+I441ZHat9nfmV4jY+SWRxbium9/Q7pEsWw0GhVIvoZ1DdQH8TFd4AIrf7Hn6OZFh4l0CDZ3amJMfgeAe4kQwlo2ygb3IuQ62Gj0kJI0ej7adcXTH96YxCLpdrDuVa9iK5ZoyJ0qzRFNLHJrwXnBYhixq5vfiWmALUsBD6txuuYX9ETCTJMUSdim2Fnw1TdOqVppPPhJPfPFoS8LliUWauw5Gq2par6SFA2pKPSE5hzDSKQD/GqaHHyxXZ6TxzN9Z7Ge4ZJYpnMV2YwzYA1OjjhdKAqARtz1ztKOmD6g+GlgiN3QU+BeV6Wuxw27ixh/NwqMu4lZcrVtOCvINQJ0h3XqNHiBDKryi3TzfVE5otm5e6h3UGdrHf4jau5PeKTYTXEkfUxk+zQLHbu/ajpMFD/FFRyP8NSXcTvTJV7E0r9C7MQRxbZ7YlUI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
